### ISSUE TITLE
Outline 1.0.2 for macOS forgets servers after restarting it

### ISSUE THREAD

**Issue by ricardbejarano** [Jigsaw-Code/outline-apps#100]
Outline 1.0.2 for macOS does not persistently store servers, so if you quit Outline and open it again, your servers are not there anymore.

Issues like this, #98 or #93 should not pass the tests before getting into the Mac App Store.

**Comment by alalamav** [comment]
@bjrnio, thanks for your feedback and sorry that you're experiencing this issue. We are aware of this problem and are trying to figure out ways to fix it; unfortunately it has been challenging to reproduce it in a development environment. I have some questions that could help us:

* Could you please tell me what macOS and Outline versions you are running?
* Are the servers getting deleted every time you quit the app? 
  * If you can reproduce it reliably, it may be helpful to list the contents of the following directory before and after the servers are removed:
  * `~/Library/Containers/org.outline.macos.client/Data/Library/Application\ Support/org.outline.macos.client/`.
  * This path contains the database used to store the server configurations; the files in this directory could be getting deleted or corrupted.
* Does rebooting also cause the servers to get deleted?

**Comment by bjrnio** [comment]
I've been trying to reproduce it and it's not exactly as I though it was, but:

On a clean system:
- Install Outline
- Open Outline and add a server
- Can connect/disconnect to/from the server
- Quit Outline from the menu bar button
- Open Outline again
- **There are no servers**

I think it might have something to do with the "Quit" button on the menu, when I quitted Outline with `CMD+Q`, the issue went away, but it just might be a coincidence.

```
# Outline installed, servers gone:
$ ls ~/Library/Containers/org.outline.macos.client/Data/Library/Application\ Support/org.outline.macos.client/
ls: /Users/caretaker/Library/Containers/org.outline.macos.client/Data/Library/Application Support/org.outline.macos.client/: No such file or directory
```

macOS: `10.13.4`
Outline: `1.0.2`

Note 1: I tested it on two different Macbook models, both running 10.13.4 and Outline 1.0.2
Note 2: sorry if I'm not doing too much research, right now I'm pretty busy.

**Comment by alalamav** [comment]
@bjrnio, thank you for following up; this is very useful. I'll try to reproduce and get back to you.

**Comment by alalamav** [comment]
I was able to reproduce this issue. These are the steps I followed for a successful installation:
  1. Install Outline in a clean system (i.e. reboot the machine before installing).
  3. Open Outline. At this point the app should create a plist file that stores the WebView preferences (including the local storage database path): `~/Library/Containers/org.outline.macos.client/Data/Library/Preferences/org.outline.macos.client.plist
`.
  4. Quit Outline (see the last section for an explanation of why this is necessary).
  5. Open Outline and add a server. The app should create the local storage database files at `~/Library/Containers/org.outline.macos.client/Data/Library/Application\ Support/org.outline.macos.client/`.
  6. Restart the app. The servers should be displayed in the UI.  

Now, onto the issue. 
* `cfprefsd` is a daemon that provides preferences services for the `CFPreferences` and `NSUserDefaults` APIs. 
* There seems to be a [bug](https://forums.developer.apple.com/thread/88811) in `NSUserDefaults` in macOS 13 (High Sierra) that causes `cfprefsd` to enter an state in which it is unable to create the plist file. 
  * In Outline's case, this means that the WebView is unable to read the local storage DB path and fails to create it.

Issue reproduction steps:
 1. Force `cfprefsd` into this state: quit Outline and delete `~/Library/Containers/org.outline.macos.client/Data/Library/Application\ Support/org.outline.macos.client`.
    * I am not sure how else `cfprefsd` can get into this state, but this [report](https://source.ind.ie/better/app/commit/6854c4dbf2d4ff67fd340d49ffed4b7e2930feb1) suggest there is a bad interaction between the app sandbox and `cfprefsd` when deleting the container directory.
  2. Open the Console app and filter for "outline" logs.
  3. Open Outline. The deleted directory will be recreated, but `cfprefsd` will fail to create the plist with the WebView's preferences. The logs will show the following error message when the app attempts to persist the WebView's preferences:
```
attempt to set <private> for key in <private> in non-persistent preferences domain CFPrefsPlistSource<0x6000000e8200> (Domain: org.outline.macos.client, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes)
```
  4. At this point the app will not be able to persist any data in local storage.

As detailed in this [post](https://stackoverflow.com/questions/19292134/my-sandboxed-app-was-running-fine-in-10-8-but-in-10-9-it-seems-that-user-default), the solution is to reboot the machine or kill the `cfprefsd` process via:
`ps auwx | grep cfprefsd | grep -v grep | awk '{print $2}' | xargs sudo kill -2` and re-start the app.

Unfortunately, this is not the end of the story... I have noticed that the first time the app runs (after installation or after deleting the container directory), it is unable to create the local storage database files, even though the WebView's plist is created successfully. However, restarting it causes the servers to be persisted. I have yet to find the root cause for this problem, but a potential solution could be to restart the app on first run to ensure the DB files can be created on subsequent runs.

**Comment by bjrnio** [comment]
Yeah sure!

I plan to reproduce both, success and failure on both machines this weekend, with a more rigorous procedure. I just don't have the time right now.

**Comment by bjrnio** [comment]
What I did to reproduce the issue, and subsequently fix it:

1. Removed `Outline.app` and `org.outline.macos.client`, as well as some other Outline-related folders (running `$ sudo find / -name "*outline*"` yields to no related results).
2. Rebooted.
3. Installed Outline.app 1.0.2
4. Opened Outline.app and added a server, can connect
5. Quitted Outline.app with the "Quit" button
6. Opened Outline.app, the server isn't there anymore
7. Added the server again, can connect
8. Quitted Outline.app with the "Quit" button
8. Opened Outline.app, the server has now persisted

**So it looks like what you said about first-run persistance.**

I guess the difference of outcome of `Cmd+Q` was just me quitting Outline at step `4.` and it _felt_ like it fixed it, because from `8.` on, you can quit and open Outline.app no matter how many times, that servers persist.

> As for the issue with cfprefsd we could attempt to restart it, though that could be tricky given that our app is sandboxed and the command requires root access.

Do not give Outline.app root access, please. Outline.app uses ElectronJS and with the current state of Electron's security, where it's having plenty RCE bugs found by the minute, I wouldn't use an app that runs on top of Electron with root permissions.

**Comment by bmy** [comment]
It's been two months...anything? Fortunately our Outline deployment was a sort of dry run for this NGO client...I guess we'll be using Algo.

**Comment by jamesxu123** [comment]
Now experiencing this with macOS outline manager too. Now both client and manager servers are gone.

**Comment by bmy** [comment]
Sad to say but this project is unreliable and unsuitable for prime time. Insane that this has Google (“Alphabet”) backing. In the morning I’ll move my NGO client – who relies on VPN and other tech *in conflict affected and high risk areas* – to Algo (we weren’t using Outline in production anyway, only testing it). I recommend that anyone reading this check Algo out.

**Comment by trevj** [comment]
Oh man, still happening for me on Mojave. @ricardbejarano Thank you so much for helping us work through this.

I think the first/second run thing might be a red herring:
- `rm -fR ~/Library/Containers/org.outline.macos.client`
- `/Applications/Outline.app/Contents/MacOS/Outline`
- you should see the TOS
- click GOT IT
- quit
- `/Applications/Outline.app/Contents/MacOS/Outline`
- you will see the TOS

Repeat the last four steps as often as you like, you will always see the TOS - even though that just sets something in localStorage. Maybe there's something about what/how we persist following a connection that somehow - completely accidentally - works around the bug?

@alalamav FYI

**Comment by trevj** [comment]
So, I spent a few hours at this on Friday. There's something really weird going on with Web Storage: *some* weird sequence of actions is required in order to initialise Web Storage *properly*. I tried all sorts of things, e.g. reading and writing to multiple Web Storage buckets on startup but nothing I did *reliably* initialises the Web Storage database - you basically have to fiddle about with the app and connect/disconnect a few times in order for it to initialise. So weird, sorry.

**Comment by MasterGroosha** [comment]
This is still an issue, btw. Just went through updating macOS Sonoma to the newest minor version, and after reboot all the configs are gone

**Comment by bigbgh** [comment]
I'd suggest moving to WireGuard https://www.wireguard.com It gets much more
attention.

**Comment by MasterGroosha** [comment]
@bigbgh Thank you for the suggestion. I already use Wireguard to access local resources on the other side of the tunnel, but my original idea was to replace WG completely with something a little bit less detectable for network barbarians (government censors).
I guess I'll start looking for some other alternative.

**Comment by fortuna** [comment]
This is an old issue from 2018 that was fixed. If there’s a new issue, please file a new one with the details.
