### ISSUE TITLE
Cannot connect to the Internet using Outline

### ISSUE THREAD

**Issue by GeliusIHe** [Jigsaw-Code/outline-apps#1771]
**Describe the bug**
I connect to the server, no errors, but after connection the internet disappears. (accordingly, when I go to the sites I just get a load (about a minute), and then exit to an error. )

**Expected behavior**
There should be a successful connection to the vpn, the internet should not be lost.

**Screenshots**
![image](https://github.com/Jigsaw-Code/outline-client/assets/42354288/a8c70513-ffe4-48a4-9783-5ec07397f14a)
![image](https://github.com/Jigsaw-Code/outline-client/assets/42354288/57e48f6e-728c-41ec-aae9-b6dc515a7b28)

**Client system (please complete the following information):**
 - Outline Client Version: 1.12.1 (471860)
 - Your Operating System: Windows 11 22H2 22621.2506

**Additional context**
Tried and didn't help:

    turn off firewall (windows firewall)
    turn off antivirus (defender)
    reinstall client
    reinstall server
    tap adapter removal

**Comment by maddyhof** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
