### ISSUE TITLE
windows 11: failed to install `outline-tap0` driver

### ISSUE THREAD

**Issue by BokDan93** [Jigsaw-Code/outline-apps#1988]
Version 1.13.0
An error occurs at startup, launching the add_tap_device file.bat does not help to fix the problem, there is no TAP-Windows V9 adapter in the services. I tried to make all the recommendations from this topic, nothing helped: 
https://github.com/Jigsaw-Code/outline-server/issues/1431

Reinstalling Outline did not help. There are no other VPN applications, the system is completely clean

**Comment by jyyi1** [comment]
Hi @Snysnym , from the error, we failed to install the OpenVPN tap device driver on your system. Maybe you have already installed other VPN products before, or maybe some anti-virus tool is blocking your from installing the driver. We're hoping to find a way to avoid needing this driver in the future. But for now, you may try to reinstall the tap device driver manually (the installation script is located at `C:\Program Files (x86)\Outline\add_tap_device.bat`, and the installation binary is located at `C:\Program Files (x86)\Outline\tap-windows6`). If it installs successfully, an `outline-tap0` device should appear in the network adapters list:

![image](https://github.com/Jigsaw-Code/outline-apps/assets/93548144/9dc16bda-eb1f-4e67-89a6-cd642f5ec1a1)

**Comment by jyyi1** [comment]
Hi @BokDan93 , from your debug screenshot in https://github.com/Jigsaw-Code/outline-apps/issues/1798#issuecomment-2068636627, it seems you have a similar issue that Outline failed to install the OpenVPN tap device driver. Because there should be an `outline-tap0` device in the network adapter list (check the screenshot I pasted in https://github.com/Jigsaw-Code/outline-apps/issues/1988#issuecomment-2070767154).

Outline won't be able to connect until that device is successfully installed. Also as I mentioned before, since this drive is a third-party binary, we don't have any control over it, so for now the only way is try to manually reinstall the drive (the installation script is located at `C:\Program Files (x86)\Outline\add_tap_device.bat`, and the driver binary is located at `C:\Program Files (x86)\Outline\tap-windows6`). Here is source code of the OpenVPN's driver: https://github.com/OpenVPN/tap-windows6 .

**Comment by jyyi1** [comment]
Root cause: [OemVista.inf](https://github.com/Jigsaw-Code/outline-apps/blob/master/third_party/tap-windows6/bin/amd64/OemVista.inf) should be `CRLF` line ended instead of `LF`. We made a change two months ago which caused this regression: https://github.com/Jigsaw-Code/outline-apps/pull/1913 .  Will fix it soon.

**Comment by Snysnym** [comment]
> Hi @Snysnym , from the error, it seems Outline failed to install the OpenVPN tap device driver on your system. Maybe you have already installed other VPN products before, or maybe some anti-virus tool is blocking your from installing the driver. We're hoping to find a way to avoid needing this driver in the future. But for now, you may try to reinstall the tap device driver manually (the installation script is located at `C:\Program Files (x86)\Outline\add_tap_device.bat`, and the driver binary is located at `C:\Program Files (x86)\Outline\tap-windows6`). If it installs successfully, an `outline-tap0` device should appear in the network adapters list:
> 
> ![image](https://private-user-images.githubusercontent.com/93548144/324587151-9dc16bda-eb1f-4e67-89a6-cd642f5ec1a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MTc4NTIsIm5iZiI6MTcxMzgxNzU1MiwicGF0aCI6Ii85MzU0ODE0NC8zMjQ1ODcxNTEtOWRjMTZiZGEtZWIxZi00ZTY3LTg5YTYtY2Q2NDJmNWVjMWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDIwMjU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZmUyMmQ3ZDYyZGRkMjE4MTBhNDAzNjRlNTZmMTVjNTEwOTdkYTEwZDQzMzVhMzEwMDE4ZGQzZjEyMjgzOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5gVo7ritfctftohdgaKceUppQNNOcO1ImuqTQ79iryI)
> 
> [#1103 (comment)](https://github.com/Jigsaw-Code/outline-apps/issues/1103#issuecomment-2058888068) mentioned another workaround, which is to install an old version of Outline, and then auto-upgrade to the latest one.

Thank you, this solution worked out!
