### ISSUE TITLE
[Bug]: iOS browsing issues when Outline is connected

### ISSUE THREAD

**Issue by btcnym** [Jigsaw-Code/outline-apps#2038]
### Application

Outline Client

### Describe the bug

Outline on a PC/Windows is fine.  Outline App on iOS all of sudden, with no recent iOS updates, is erratic.  It connects just fine, you can google things, however our company website and other websites like http://ip4.me and https://whatismyipaddress.com/ sometimes load and sometimes don't.    We are hosted on Digital Ocean, they claim no issues with hosting.  Anyone else experiencing erratic behavior when connected browsing?

### Steps to reproduce

It connects just fine, you can google things, however our company website and other websites like http://ip4.me and https://whatismyipaddress.com/ sometimes load and sometimes don't.  

### Outline Version

1.13.0

### What operation system are you using?

iOS

### Operating System Version

17.5.1

**Comment by btcnym** [comment]
a few other websites that fail to load on iOS 17...   cnn.com and espn.com

**Comment by btcnym** [comment]
All of my websites that failed to work, now load just fine when using my same Outline server using Potatso App on iOS.  I was having issues with the iOS app, I just installed Potatso and pasted my ss:// key and it all works great.  https://apps.apple.com/us/app/potatso/id1239860606    This is good, but it tells me there's some conflict with Outline and iOS, I hope this helps the devs.

**Comment by sbruens** [comment]
Thank you for reaching out! Please contact us through the application on the device where you’re experiencing this issue  – or at [support.getoutline.org](https://support.getoutline.org/) – and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org](https://support.getoutline.org/s/) for access to help articles and more.
