### ISSUE TITLE
[Bug]: Outline Manager using base 10 instead of base 2 to calculate data usage

### ISSUE THREAD

**Issue by rorosin** [Jigsaw-Code/outline-apps#2121]
### Application

Outline Manager

### Describe the bug

It's fully duplicate of #1880, cause no fixes are there.

Outline Manager app uses base-10 math (there 1 "GB" is equal to 1000^3 bytes), but Outline Server API uses proper base-2 counts (one "API"-GB is equal to 1024^3 bytes, as it should be).

### Steps to reproduce

Set traffic limit by Outline Server API, open Outline Manager and notice incorrect display of traffic limit.

### What did you expect to happen?

Outline Manager must divide by 1024^3.

### What actually happened?

It divides by 1000^3.

### Outline Version

1.15.2

### What operation system are you using?

Windows

### Operating System Version

Windows 10

### Screenshots and Videos

Here limit was set to `500` GB (`536_870_912_000` bytes) through API, but Manager shows it like `536.87` GB:
![image](https://github.com/user-attachments/assets/fb6b8705-5089-48c3-a356-5b21a6981ee1)

**Comment by rorosin** [comment]
@fortuna

**Comment by fortuna** [comment]
We intend to use gigabyte (GB) as 10^9 bytes, as per the International System of Units (SI).

That's the modern and preferred use of the unit, as it aligns with the standards and is more user-friendly. It's recommended by the International Electrotechnical Commission (IEC). Apple and Linux now use that standard (though Windows is still stuck with the old, misleading one).

The binary unit you are asking for is now called gibibyte (GiB). See https://en.m.wikipedia.org/wiki/Gigabyte.

The use of the decimal system is intentional, and it seems we are correctly using it in this case. Perhaps we can clarify in the document somewhere.
