### ISSUE TITLE
[Bug]: outline-ipc-start-proxying

### ISSUE THREAD

**Issue by tonyrostov** [Jigsaw-Code/outline-apps#2271]
### Application

Outline Client

### Describe the bug

Hello. Until November 12, 2024, the client worked correctly. Today, when I try to connect to my key, I see the error "outline-ipc-start-proxying". This error occurs only on my PC, in any of the users. The key is 100% working, I can connect to it on my MacBook and iPhone. I tried to install previous versions, and several times I followed the steps strictly according to the description on the page https://support.getoutline.org/s/article/Error-Messages Unfortunately, nothing helps me. Since November 11, I have not made any changes to Windows, did not change the adapter settings, network connections, security policies, did not touch the browser. Please tell me what else I can do?

### Steps to reproduce

1. Open the application
2. Click on the server
3. Notice the error

### What did you expect to happen?

Successful connection

### What actually happened?

Error: Error invoking remote method 'outline-ipc-start-proxying': Error

### Outline Version

1.14.0 (480311)

### What operation system are you using?

Windows

### Operating System Version

11

**Comment by acebiscuits** [comment]
try just reinstall outline app. It worked in my case

**Comment by KirkKarabyte** [comment]
> try just reinstall outline app. It worked in my case

This case not working. Win 11 24H2

**Comment by sbruens** [comment]
Thank you for reaching out! Please contact us through the application on the device where you’re experiencing this issue  – or at [support.getoutline.org](https://support.getoutline.org/) – and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org](https://support.getoutline.org/s/) for access to help articles and more.
