### ISSUE TITLE
[Bug]: Latest client broken on iOS < 17.0

### ISSUE THREAD

**Issue by moandes** [Jigsaw-Code/outline-apps#2276]
### Application

Outline Client

### Describe the bug

![07F9B2E0-C3F0-4CC4-BB8C-DDCD7B010019](https://github.com/user-attachments/assets/1be86b00-022c-4113-881c-b9e00f0942b1)

Hi
The new version of iOS released on the App Store has bugs. The key does not get added within the app, the + button at the top for adding a key is not working, and there are other issues as well.

### Steps to reproduce

The new version of iOS released on the App Store has bugs. The key does not get added within the app, the + button at the top for adding a key is not working, and there are other issues as well.

### Outline Version

1.14.0

### What operation system are you using?

iOS

### Operating System Version

ios 15.8.3

### Screenshots and Videos

![EF709FEF-5292-47DC-91A3-065AB7CFC3A0](https://github.com/user-attachments/assets/05234ff4-bd17-4df0-ae5a-04b3d9bd83f0)

**Comment by laowant** [comment]
update your system to iOS17

**Comment by moandes** [comment]
> update your system to iOS17

Thank you, but the iPhone 7 can't be updated to iOS 17, and the latest version available is 15.8.

**Comment by khantzawhein** [comment]
Any news about rolling out the bug fix on App Store anytime soon? It's been about 2 week since the last update.

Some of my clients using iOS < 17 got broken clients after app store automatically updated their Outline app, and unable to downgrade. Forcing them to use another application unless they can upgrade their iOS.

Although I understand this is open-source app by Google Lab, it's pretty disappointing to see that it's slipping obvious UI bugs to production application that literally has **"one dialog box and one button".**

Is there anyway other party can test Outline app on their devices like TestFlight for iOS? If so, please do release beta versions to public before just going straight to production.

This application is the greatest thing ever done by Google since it doesn't include any ads or bloats and stay independent of the business side, making it non-profit freeware, and I love it.

So, I want to kindly request the Outline dev team to "not break" or "drop support" for older version of OS, since many people are relying on this application to bypass their country's censorship firewall. 

And many of those countries are not "rich" in anyway (actually poorest in the world) that people can't always afford relatively new mobile phone with latest operating system.

**Comment by belyan** [comment]
Any news about when next version with fix for iOS 15 and 16 will be released in AppStore?

**Comment by sbruens** [comment]
I'll just copy here part of what I wrote in #2283:

> We're working hard to get the new release out to you all as soon as possible. Unfortunately Apple does not have a way to rollback to a previous version, so to get an update out we need to do a full new release and go through the entire release process again, which involves several steps and can unfortunately take some time.
> ...
> Thanks for your patience and understanding. We know this is frustrating.

As of today the app is with Apple for final review.

**Comment by sahanenkov** [comment]
> #2283
This issue was about MacOS what about iOS?

**Comment by sahanenkov** [comment]
> I'll just copy here part of what I wrote in #2283:
> 
> > We're working hard to get the new release out to you all as soon as possible. Unfortunately Apple does not have a way to rollback to a previous version, so to get an update out we need to do a full new release and go through the entire release process again, which involves several steps and can unfortunately take some time.
> > ...
> > Thanks for your patience and understanding. We know this is frustrating.
> 
> As of today the app is with Apple for final review.

This issue was about MacOS what about iOS?

**Comment by khxnt** [comment]
Got an update for MacOS but how's the status of the update with iOS?

**Comment by sbruens** [comment]
Apple just accepted the app and I've released **version 1.14.1**. Apple will be rolling this out in [phases](https://developer.apple.com/help/app-store-connect/update-your-app/release-a-version-update-in-phases/), so it might not be immediately available for everyone. You can either wait for the automatic update or manually update to the latest version directly from the App Store:
https://apps.apple.com/us/app/outline-app/id1356177741

If you continue to experience problems after updating, please let us know by re-opening this issue.

We appreciate everyone's patience and feedback!
