### ISSUE TITLE
[Bug]: 1.14.0 Windows - VPN Connected but traffic is not going through VPN

### ISSUE THREAD

**Issue by khantzawhein** [Jigsaw-Code/outline-apps#2281]
### Application

Outline Client

### Describe the bug

In Windows, when using 1.14.0, the VPN connects successfully, but internet traffic in and out from the PC doesn't go through the VPN Server.

Please check the screenshot.

When I uninstalled and reinstalled version 1.13, there was no such issue anymore.

### Steps to reproduce

1. Open App
2. Connect VPN
3. Connected
4. Open Browser and Check IP

### What did you expect to happen?

Should pass through VPN.

### What actually happened?

Traffic is not passing through a proxy. Thus, it displays the original ISP IP instead of the VPN's IP.

### Outline Version

1.14.0

### What operation system are you using?

Windows

### Operating System Version

11

### Screenshots and Videos

![telegram-cloud-photo-size-5-6190244542075222872-y](https://github.com/user-attachments/assets/98733317-19ec-4db7-a194-f02d5e641eb3)

**Comment by sbruens** [comment]
Thank you for reaching out! Please contact us through the application on the device where you’re experiencing this issue  – or at [support.getoutline.org](https://support.getoutline.org/) – and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org](https://support.getoutline.org/s/) for access to help articles and more.
